---
title: "Demographics of First 5 Ventura"
author: "Gwendolyn Reynolds"
date: "1/30/2018"
output:
  word_document: default
  html_document: default
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages 
library(knitr)
library(readxl)
library(scales)
library(tidyverse)
library(anonymizer)
library(lubridate)
library(forcats)
library(sorensonimpact)

si_ggplot_theme_update() 
theme_update(text = element_text(family = "Roboto"), axis.text = element_text(family = "Roboto"), strip.text = element_text(family = "Roboto"), axis.text.x = element_text(angle = 45, hjust = 1))

```


```{r read in data, include=FALSE, warning=FALSE, message=FALSE}

import_member <- read_xls("~/Google Drive/SI/DataScience/Side projects/Ventura Preschool /raw_data/IMPORT MEMBER Client Assessment by Answer Value 01-19-2018.xls")
family_intake <- read_xls("~/Google Drive/SI/DataScience/Side projects/Ventura Preschool /raw_data/FAMILY INTAKE Client Assessment by Answer Value 01-19-2018.xls")
preschool <- read_xls("~/Google Drive/SI/DataScience/Side projects/Ventura Preschool /raw_data/Clients with Preschool Services.xls")
ziptocity <- read_csv("~/Google Drive/SI/DataScience/Side projects/Ventura Preschool /raw_data/zipcodeCity.csv")

```

```{r clean and merge, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}

## get the dates in the same format
preschool$`Enrollment Date_` <- as.Date(preschool$`Enrollment Date_`, "%m/%d/%Y")
preschool$`Exited Date` <- as.Date(preschool$`Exited Date`, "%m/%d/%Y")

##I want to know the year of enrollment, so i'm creating a "year" variable
preschool <- preschool %>% 
  mutate(school_year = year(`Enrollment Date_`)) 

## this dataset has a bunch of repeat rows. I want to filter those out. 
# preschool <- preschool %>% 
#   group_by(`Program Title`, ClientID, Zip, school_year) %>% 
#   mutate(count = n()) %>% 
#   mutate(rank = rank(`Enrollment Date_`)) %>% 
#   filter(rank==1)

preschool <- preschool %>% 
  group_by(`Program Title`, ClientID, Zip, school_year) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`Enrollment Date_`)) 

### collapse all ethnicities besides white/latino/other
preschool <- preschool %>% 
    mutate(Ethnicity = as.factor(Ethnicity)) 

preschool <- preschool %>% 
    mutate(Ethnicity= (fct_collapse(Ethnicity, "Other" = c("01. Alaskan Native / American Indian", "02. Asian", "03. Black / African American", "05. Vietnamese", "06. Pacific Islander", "08. Multiracial", "09. Other", "10. Don't know/Declined")))) 


preschool <- preschool %>% 
    mutate(Language= (fct_collapse(Language, "Other" = c("03. Mixteco", "05. Vietnamese", "07. Mandarin (Putonghua)", "09. Filipino(Tagalog)", "10. Other", "11. Arabic", "13. Chinese", "15. Unknown", "16. Decline to Answer", "06. Korean", "14. Other", "08. Farsi (Persian)", "12. Cambodian", "04. Hmong", "11. Don't Know/Declined")))) 

family_intake$Assessment_Date <- as.Date(family_intake$Assessment_Date, "%m/%d/%Y")

##I want to know the year of enrollment, so i'm creating a "year" variable
family_intake <- family_intake %>% 
  mutate(school_year = year(`Assessment_Date`)) 

family_intake <- family_intake %>% 
  group_by(`Program Title`, ClientID, Zip, school_year) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`Assessment_Date`)) 

family_intake <- family_intake %>% 
    mutate(Ethnicity= (fct_collapse(Ethnicity, "Other" = c("01. Alaskan Native / American Indian", "02. Asian", "03. Black / African American", "05. Vietnamese", "06. Pacific Islander", "08. Multiracial", "09. Other", "10. Don't know/Declined")))) 


family_intake <- family_intake %>% 
    mutate(Language= (fct_collapse(Language, "Other" = c("03. Mixteco", "05. Vietnamese", "07. Mandarin (Putonghua)", "09. Filipino(Tagalog)", "10. Other", "11. Arabic", "13. Chinese", "15. Unknown", "16. Decline to Answer", "06. Korean", "14. Other", "08. Farsi (Persian)", "12. Cambodian", "04. Hmong")))) 

ziptocity <- ziptocity %>% slice(1:53) %>% mutate(Zip = as.integer(`Zip Code`)) 

family_intake <- family_intake %>% ungroup() %>% mutate(Zip = as.integer(Zip))

family_intaketest <- family_intake %>% 
  right_join(ziptocity, family_intake, by = "Zip")

family_intaketest <- family_intaketest %>% filter(!is.na(ClientID)) 

family_intaketest <- family_intaketest %>% group_by(`Program Title`, ClientID, Zip, school_year) %>% mutate(count = n()) %>% 
  mutate(rank = rank(`Assessment_Date`)) 

family_intaketest %>% 
  group_by(rank) %>% 
  summarise(count = n())

notpre <- c("01: Preschool (Marina West)", "Preschool (Berylwood)", "Preschool (Hathaway School)", "Preschool (Sierra Linda)", "Preschool {Hueneme Head Start}", "Preschool {Larsen Head Start}", "Preschool {Little Vikings Head Start}", "Preschool {Parkview Head Start}")
`%notin%` <- Negate(`%in%`)

preschool <- preschool %>% 
  filter(`Service Modality` %notin% notpre)

preschool %>% 
  group_by(`Service Modality`) %>% 
  count(`Service Modality`)

preschool <- preschool %>% ungroup %>% mutate(dataset = "preschool") %>% mutate(Zip = as.integer(Zip))
family_intake <- family_intake %>% ungroup %>%  mutate(dataset = "family") %>% mutate(Zip = as.integer(Zip))

family_intake <- family_intake %>% mutate(wherelive = `01-10: 10 Where does your family currently live?`) %>% 
rename(education = "01-1: 1 What is your highest level of education", 
  wherelive = "01-10: 10 Where does your family currently live?" ,               
  employment = "01-2: 2 What is your current employment status?"    ,             
  maritalstatus = "01-3: 3 What is the marital status of the adults?"    ,           
  income = "01-4: 4 What was your total FAMILY INCOME in the last 12 months?",
  smoke = "01-5: 5 Does anyone in your household smoke?"   ,                 
  childrenhouse = "01-6: 6 How many children in your household are 0-5 years old?"  ,
  householdmems = "01-7: 7 How many family members live in your household? (incl_ a",
  health = "01-8: 8 Do all family members in your home have health coverage" ,
  pregmom = "01-9: 9 Is there an expectant mother in the home?")

preschool2 <- preschool %>% filter(FamilyID!=0)
mergedpreschool <- left_join(preschool2, family_intake, by = c("FamilyID" = "FamilyID"))

mergedpreschool <- mergedpreschool %>% mutate(school_year = ifelse(school_year.x==school_year.y, 1, 0))

mergedpreschool %>% 
  ungroup() %>% 
  count(school_year)

mergedpreschool <- mergedpreschool %>% 
  group_by(school_year.x, ClientID.x) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`)) 

mergedpreschool %>% 
  group_by(school_year) %>% 
  count(rank)

mergedpreschool <- mergedpreschool %>% 
  mutate(dataset = ifelse(is.na(dataset.y), "preschool only", 
                   ifelse(dataset.y=="family", "family", "neither"))) 

mergedpreschool %>% 
  ungroup() %>% 
  count(dataset)

mergedpreschool %>% 
  filter(dataset=="family") %>% 
  group_by(school_year) %>% 
  count(count)

mergedpreschool %>% 
  filter(count==6) %>% 
  print()
```

```{r deduplicate, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
distinct_rows <- mergedpreschool %>% select("ClientID.x","DOB.x", "school_year.x", "Ethnicity.x", "Language.x", "Gender_.x", "Special Needs", "Zip.x", "education", "wherelive", "employment", "maritalstatus", "income", "householdmems", "school_year.y") %>% distinct()

distinct_rows <- distinct_rows %>% 
  group_by(school_year.x, ClientID.x) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`))

distinct_rows %>% 
  filter(rank==1.5) %>% 
  print()

distinct_rows %>% 
  ungroup() %>% 
  count(rank)

distinct_rows <- distinct_rows %>% 
  mutate(double = ifelse(income=="No answer/prefer not to say" & count>1, "1", "0")) %>% 
  filter(double!=1)

distinct_rows <- distinct_rows %>% 
  group_by(school_year.x, ClientID.x) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`))

distinct_rows %>% 
  ungroup() %>% 
  count(rank)

distinct_rows <- distinct_rows %>% 
  select("ClientID.x","DOB.x", "school_year.x", "Ethnicity.x", "Language.x", "wherelive", "employment", "maritalstatus", "income", "householdmems", "Gender_.x", "Special Needs", "Zip.x", "school_year.y") %>% distinct()

distinct_rows <- distinct_rows %>% 
  group_by(school_year.x, ClientID.x) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`))

distinct_rows %>% 
  ungroup() %>% 
  count(rank)

distinct_rows <- distinct_rows %>% 
  mutate(double = ifelse(employment=="No answer/prefer not to say" & count>1, "1", "0")) %>% 
  filter(double!=1)

distinct_rows <- distinct_rows %>% 
  group_by(school_year.x, ClientID.x) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`))

distinct_rows %>% 
  ungroup() %>% 
  count(rank)

distinct_rows <- distinct_rows %>% 
  select("ClientID.x","DOB.x", "school_year.x", "Ethnicity.x", "Language.x", "income", "householdmems", "Gender_.x", "Special Needs", "Zip.x", "school_year.y") %>% distinct()

distinct_rows <- distinct_rows %>% 
  group_by(school_year.x, ClientID.x) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`))

distinct_rows <- distinct_rows %>% 
  group_by(school_year.x, ClientID.x) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.y`))

distinct_rows <- distinct_rows %>% 
  filter(rank==1)

distinct_rows <- distinct_rows %>% 
  group_by(school_year.x, ClientID.x) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`))

# distinct_rows <- distinct_rows %>% 
#   filter(count==1) 

distinct_rows %>% 
  ungroup() %>% 
  count(income)

### merge client IDs where family ID is 0. 
preschool3 <- preschool %>% filter(FamilyID==0) 
mergedpreschool2 <- left_join(preschool3, family_intake, by = c("ClientID" = "ClientID"))

mergedpreschool2 <- mergedpreschool2 %>% mutate(school_year = ifelse(school_year.x==school_year.y, 1, 0))

mergedpreschool2 <- mergedpreschool2 %>% 
  group_by(school_year.x, ClientID) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`)) 

mergedpreschool2 <- mergedpreschool2 %>% 
  mutate(dataset = ifelse(is.na(dataset.y), "preschool only", 
                   ifelse(dataset.y=="family", "family", "neither"))) 

# unique_rows <- !duplicated(mergedpreschool[c("ClientID.x","DOB.x", "school_year.x", "Ethnicity.y", "Language.y", "education", "wherelive", "employment", "maritalstatus", "income", "householdmems")])

distinct_rows2 <- mergedpreschool2 %>% select("ClientID","DOB.x", "school_year.x", "Ethnicity.x", "Language.x", "Gender_.x", "Special Needs", "Zip.x", "education", "wherelive", "employment", "maritalstatus", "income", "householdmems", "school_year.y") %>% distinct()

distinct_rows2 <- distinct_rows2 %>% 
  group_by(school_year.x, ClientID) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`))

distinct_rows2 %>% 
  filter(rank==1.5) %>% 
  print()

distinct_rows2 <- distinct_rows2 %>% 
  mutate(double = ifelse(income=="No answer/prefer not to say" & count>1, "1", "0")) %>% 
  filter(double!=1)

distinct_rows2 <- distinct_rows2 %>% 
  group_by(school_year.x, ClientID) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`))

distinct_rows2 <- distinct_rows2 %>% 
  select("ClientID","DOB.x", "school_year.x", "Ethnicity.x", "Language.x", "wherelive", "employment", "maritalstatus", "income", "householdmems", "Gender_.x", "Special Needs", "Zip.x", "school_year.y") %>% distinct()

distinct_rows2 <- distinct_rows2 %>% 
  group_by(school_year.x, ClientID) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`))

distinct_rows2 <- distinct_rows2 %>% 
  mutate(double = ifelse(employment=="No answer/prefer not to say" & count>1, "1", "0")) %>% 
  filter(double!=1)

distinct_rows2 <- distinct_rows2 %>% 
  group_by(school_year.x, ClientID) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`))

distinct_rows2 <- distinct_rows2 %>% 
  select("ClientID","DOB.x", "school_year.x", "Ethnicity.x", "Language.x", "income", "householdmems", "Gender_.x", "Special Needs", "Zip.x", "school_year.y") %>% distinct()

distinct_rows2 <- distinct_rows2 %>% 
  group_by(school_year.x, ClientID) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.y`))

distinct_rows2 %>% 
  ungroup() %>% 
  count(rank)

distinct_rows2 <- distinct_rows2 %>% 
  filter(rank==1) 

distinct_rows2 %>% 
  ungroup() %>% 
  count(income)

distinct_rows <- distinct_rows %>% 
  rename(ClientID = ClientID.x)

distinct_rowstotal <- bind_rows(distinct_rows, distinct_rows2)

distinct_rowstotal <- distinct_rowstotal %>% 
  group_by(school_year.x, ClientID) %>% 
  mutate(count = n()) %>% 
  mutate(rank = rank(`school_year.x`))

distinct_rowstotal %>% 
  ungroup() %>% 
  count(count)

distinct_rowstotal <- distinct_rowstotal %>% 
  rename(school_year = school_year.x) %>% 
  rename(Ethnicity = Ethnicity.x) %>% 
  rename(Language = Language.x) %>% 
  rename(Gender = Gender_.x) %>% 
  rename(Zip = Zip.x)

distinct_rowstotal <- distinct_rowstotal %>% 
  group_by(ClientID) %>% 
  mutate(repeats = n()) %>% 
  mutate(rank = rank(`school_year`))

distinct_rowstotal %>% 
  ungroup() %>% 
  count(repeats)


```

```{r merged and deduplicated data, echo=FALSE}

distinct_rowstotal %>% 
   group_by(school_year) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
   kable()

distinct_rowstotal %>% 
   group_by(school_year) %>%
  summarise(count = n()) %>% 
  ggplot(aes(x=school_year, y=count)) +
  geom_col()+
  labs(x="School Year", y="Total Number") +
  ggtitle("Total Number of Preschoolers by School Year")


distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(Ethnicity)) %>% 
  group_by(Ethnicity) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
   kable()

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(Ethnicity)) %>% 
  group_by(school_year, Ethnicity) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
   kable()

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(Ethnicity)) %>% 
  group_by(Ethnicity) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
  ggplot(aes(x=Ethnicity, y=perc)) +
  geom_col()+
  labs(x="Ethnicity", y="Percent") +
  ggtitle("Ethnicity by Preschoolers")


distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(Language)) %>% 
  group_by(Language) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
   kable()

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(Language)) %>% 
  group_by(school_year, Language) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
   kable()

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(Language)) %>% 
  group_by(Language) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
  ggplot(aes(x=Language, y=perc)) +
  geom_col()+
  labs(x="Language", y="Percent") +
  ggtitle("Language Spoken by Preschoolers")

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(income)) %>% 
  group_by(income) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
   kable()

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(income)) %>% 
  group_by(school_year, income) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
   kable()

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(income)) %>% 
  group_by(income) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
  ggplot(aes(x=income, y=perc)) +
  geom_col()+
  labs(x="income", y="Percent") +
  ggtitle("Family Income")

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(householdmems)) %>% 
  ungroup %>% 
  mutate(householdmems = as.numeric(householdmems)) %>% 
  summarise(meanHouseholdMembers = mean(householdmems, na.rm = TRUE)) %>% 
   kable()

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(householdmems)) %>% 
  group_by(school_year) %>% 
  mutate(householdmems = as.numeric(householdmems)) %>% 
  summarise(meanHouseholdMembers = mean(householdmems, na.rm = TRUE)) %>% 
   kable()

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(householdmems)) %>% 
  group_by(school_year) %>% 
  mutate(householdmems = as.numeric(householdmems)) %>% 
  summarise(meanHouseholdMembers = mean(householdmems, na.rm = TRUE)) %>% 
  ggplot(aes(x=school_year, y=meanHouseholdMembers)) +
  geom_col()+
  labs(x="School Year", y="Mean Household Members") +
  ggtitle("Mean Household Members by School Year")

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(Gender)) %>% 
  group_by(Gender) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
   kable()

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(Gender)) %>% 
  group_by(school_year, Gender) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
   kable()

distinct_rowstotal %>% 
  filter(school_year>=2014) %>% 
  filter(!is.na(Gender)) %>% 
  group_by(Gender) %>%
  summarise(count = n()) %>% 
  mutate(perc=(count/sum(count)*100)) %>% 
  ggplot(aes(x=Gender, y=perc)) +
  geom_col()+
  labs(x="Gender", y="Percent") +
  ggtitle("Gender of Preschoolers")



```

```{r, include=FALSE}
##below is my attempt to collapse, rather than merge
# mergedpreschool2 <- bind_rows(preschool, family_intake)
# 
# mergedpreschool2 <- mergedpreschool2 %>% group_by(ClientID) %>% mutate(rank = rank(ClientID))
# 
# mergedpreschool2 %>% ungroup() %>% count(dataset, rank)
# 
# mergedpreschool2 %>% 
#   group_by(dataset, `01-1: 1 What is your highest level of education`) %>% 
#   count(`01-1: 1 What is your highest level of education`)
# 
# mergedpreschool2 %>% 
#   group_by(ClientID) %>% 
#   group_by(`01-1: 1 What is your highest level of education`) %>% 
#   count()
# 
# mergedcollapse <- mergedpreschool2 %>%
#   filter(school_year>=2014) %>% 
#   group_by(ClientID) %>%
#   summarise(education=paste(`01-1: 1 What is your highest level of education`, collapse=' '), school_year = paste(school_year, collapse = " "), school_year = paste(school_year, collapse = " "), ProgramTitle = paste(`Program Title`, collapse = " "), dob = paste(DOB, collapse = " "), gender = paste(Gender_, collapse = " "), sped = paste(`Special Needs`, collapse = " "), ethnicity = paste(Ethnicity, collapse = " "), language = paste(Language, collapse = " "), city = paste(City, collapse = " "), zip = paste(Zip, collapse = " "), dataset = paste(dataset, collapse = " "), preschool = paste(`Service Modality`, collapse = " "), employ = paste(`01-2: 2 What is your current employment status?`, collapse = " "), income = paste(`01-4: 4 What was your total FAMILY INCOME in the last 12 months?`, collapse = " "), householdmems = paste(`01-7: 7 How many family members live in your household? (incl_ a`, collapse = " ")) 
# 
# mergedcollapse %>% 
#   count(dataset) 
# 
# 
# mergedcollapse <- mergedcollapse %>% 
#   mutate(datasetsimple = ifelse(grepl("preschool family", dataset), "preschool family",
#                          ifelse(grepl("family", dataset), "family", 
#                          ifelse(grepl("preschool", dataset), "preschool", 
#                           "other"))))
# 
# mergedcollapse %>% 
#   count(education)
#     
```




